name: test

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  format:
    name: gleam format --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.3"
          rebar3-version: "3"
      - run: gleam format --check src test

  test:
    name: gleam test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.3"
          rebar3-version: "3"
      - uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-gleam-${{ hashFiles('manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-
      - run: gleam deps download
      - run: gleam test
